apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: filebeat-filebeat
  name: filebeat-filebeat-config
  namespace: default
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - "/mnt/stats-*.log"
      fields_under_root: true
      # json.message_key: "message"
      json.keys_under_root: true
      json.overwrite_keys: true
      json.add_error_key: false
  #     exclude_lines: ["^/fonts/", "^/img/", "^/js/", "^/styles/", "^/transfers?size=30"]
  #     fields:
  #       index_prefix: stats
    output.elasticsearch:
      host: '${NODE_NAME}'
      index: "api-access-%{+yyyy.MM.dd}"
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
    setup.template:
      name: 'api-access'
      pattern: 'api-access-*'
      enabled: false
