apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    meta.helm.sh/release-name: filebeat
    meta.helm.sh/release-namespace: default
  labels:
    app: filebeat-filebeat
    app.kubernetes.io/managed-by: Helm
    chart: filebeat-7.10.1
    heritage: Helm
    release: filebeat
  name: filebeat-filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - "/mnt/*.json"
      fields_under_root: true
      # json.message_key: "message"
      json.keys_under_root: true
      json.overwrite_keys: true
      json.add_error_key: false
    output.elasticsearch:
      host: '${NODE_NAME}'
      hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
